spring.application.name=mercaditolibre

#Asignación de puerto
server.port=8085
#Conexi+on a la base de datos
spring.datasource.url=jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

##Coniguración de JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#Configuracón global de cors para react
spring.mvc.cors.allowed-origins=http://localhost:5173
spring.mvc.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS

#Propiedades de seguridad
app.jwt.secret=006aa498da0c6c4e1977a3d3c5799552fc9123557be9c93bb6c2d740878ccceb
app.jwt.expiration-ms=86400000

#Stripe Configuration
stripe.secret.key=${STRIPE_SECRET_KEY}
stripe.webhook.secret=${STRIPE_WEBHOOK_SECRET}
stripe.currency=mxn
stripe.business.name=Mercadito Libre

#FrontEnd 
frontend.url=http://localhost:5173




